name: Debugging with SSH
on: 
  schedule:
    - cron: 00 */6 * * *
  watch:
    types: [started]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1
          
     - name: gd2od
       run: curl -sL https://raw.githubusercontent.com/baipiaowang123/baipiaoking/master/gd2od.sh | bash
         

     
         
 

